### ISSUE TITLE
`m ls` throws warning

### ISSUE THREAD

**Issue by creynders** [aheckmann/m#17]
Hi there,

Just a heads-up since it works correctly, but when I run `m ls` I get the following warnings before the list of possible versions:

```sh
/usr/local/bin/m: command substitution: line 469: syntax error near unexpected token `|'
/usr/local/bin/m: command substitution: line 469: `    | awk '{ print "  " $1 }''
```

This is on Mac OS X 10.10.1, with `m` v1.0.0

**Comment by aheckmann** [comment]
your fix is in 1.0.1. thanks again.
