### ISSUE TITLE
m wont run without sudo

### ISSUE THREAD

**Issue by niccottrell** [aheckmann/m#31]
I just did a fresh install of npm via brew - all done without sudo. But running `m` gives as my user gives

```
mkdir: /usr/local/m/versions: Permission denied
Error: Failed to create versions directory (/usr/local/m/versions), do you have permissions to do this?
```

but `sudo m` is happy. Is this an issue installing via npm? How do I fix this correctly so that I don't have to sudo to use `m` ?

**Comment by stvnmntjy** [comment]
Take a look at the Details section in the README: https://github.com/aheckmann/m#details.

Basically, set `M_PREFIX` to a directory your user account has write privileges to.

**Comment by niccottrell** [comment]
Thanks!
