### ISSUE TITLE
Problem setting up on Amazon Linux 1

### ISSUE THREAD

**Issue by niccottrell** [aheckmann/m#52]
I’m trying to install `m` on Amazon Linux 1, with the following steps

1. `npm install -g m --build-from-source` 
1. `m 4.0.10`

but then launching `mongo` gives:
```mongo: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by mongo)```

amzn1 seems to be shopping with glibc 2.17 only.

Can I force m to compile mongo rather than just install the binary?

**Comment by stennie** [comment]
@niccottrell Can you confirm the contents of `/etc/os-release`? It looks like the distro detection is pulling the image for Amazon Linux 2 instead of 1.

Thanks,
Stennie

**Comment by niccottrell** [comment]
cat /etc/os-release

> NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

uname -a:
> Linux ip-172-31-35-239 4.14.121-85.96.amzn1.x86_64 #1 SMP Wed May 22 00:45:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

AMI:
> amzn-ami-hvm-2018.03.0.20190514-x86_64-gp2 (ami-0f962299dc4d90c81)
