### ISSUE TITLE
Update M_PREFIX behaviour to default to a writeable directory

### ISSUE THREAD

**Issue by stennie** [aheckmann/m#54]
To simplify installation, the M_PREFIX environment variable should default to the user's home directory instead of `/usr/local/`. The `/usr/local` default originates from `npm install -g`.

Expected behaviour variation for `npm` installation:
 - if M_PREFIX is not set, infer default via basepath for `m` (see: https://docs.npmjs.com/files/folders#tldr)

Expected behaviour for install via `wget`:
 - if M_PREFIX is not set but `/usr/local/m` exists and is writeable, use `/usr/local/m`
 - if M_PREFIX is not set but `/usr/local/m` exists and is not writeable, exit with message recommending `sudo chown -R $(whoami) /usr/local/m`
 - if M_PREFIX is not set and `/usr/local/m` doesn't exist, use `~/m`

General behaviour:
 - if M_PREFIX is set, use this base path
 - if M_PREFIX is set but the path isn't writeable, exit with message recommending `sudo chown -R $(whoami) $M_PREFIX`

**Comment by p-mongo** [comment]
`~/m` is rather dangerous, I frequently use single and double letter directory names for things I work with often. `~/.m` is a safer choice, there is also `~/.local` that e.g. python uses hence `~/.local/m` is perhaps an even better choice.

**Comment by stennie** [comment]
@p-mongo Apparently `.local` is part of the [XDG spec](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory) so that seems a reasonable default. Thanks for the suggestion!

Agree on behaviour for non-mutating operations: only need to exit with an error if write access is required and the destination path is non-writeable.

Regards,
Stennie
