### ISSUE TITLE
Unable to install 4.3 with m

### ISSUE THREAD

**Issue by eppingere** [aheckmann/m#55]
I was wondering if it is able to get support for 4.3 and development versions. Thanks 😄

**Comment by p-mongo** [comment]
4.3 has not had any releases yet, I don't think m will be able to install it presently.

**Comment by p-mongo** [comment]
Per the readme, `m custom` permits installing arbitrary tarballs, though it is still on the user to locate and enter the correct full URL (which normally is what m does).

**Comment by stennie** [comment]
@p-mongo is correct. There are currently no 4.3.0 binary releases:

```
m 4.3 --latest

>> Checking for latest release of MongoDB 4.3
Error: Could not find any releases for the requested version
```
If you have the prerequisite build toolchain installed you could try to build from source using `m`, but that's definitely a path of adventure.

@eppingere If you want to find out when new binary releases are available for testing, subscribe to: https://groups.google.com/group/mongodb-announce.

Barring any unexpected package renames, new development releases should work as soon as they are announced. If a released binary package can't be downloaded through `m`, please create a GitHub issue.

Regards,
Stennie
