### ISSUE TITLE
`m latest` outputs 226.0.1

### ISSUE THREAD

**Issue by ohEmily** [aheckmann/m#80]
I noticed that the `latest` command referred to in the README gives unexpected output.

```
emily.pakulski@M-V036M19369:~/mms (master %) $ m latest                                                         
MongoDB version 226.0.1 is not installed.
```

**Comment by stennie** [comment]
Thanks for reporting @ohEmily, will look into the bug. Looks like a regex match gone astray :)

Cheers,
Stennie

**Comment by ohEmily** [comment]
Thank you!
