### ISSUE TITLE
Not able to run m commands (Windows)

### ISSUE THREAD

**Issue by pstrings** [aheckmann/m#84]
I have the m file in the path that the command is trying to access but instead it's throwing an error.
![image](https://user-images.githubusercontent.com/29589412/215713117-ce426970-fb7f-41e1-8108-ab675916399b.png)

Here's the file in the exact path.
![image](https://user-images.githubusercontent.com/29589412/215713278-0b1f9ac6-bfb9-4e35-ad00-08328ac5e6ed.png)

**Comment by Batega21** [comment]
Hello, I have the same issue.
Steps I made:
Added the path to the "Path" environment variables
Open a new terminal (Powershell and CMD)

My path: 
C:\Users\myName\AppData\Roaming\npm\node_modules\m\bin
